### ISSUE TITLE
Have lots of problems with Catalina(Beta)

### ISSUE THREAD

**Issue by czg1997** [johnnync13/Xiaomi-Notebook-Air-1Gen#20]
Hi Johnny,

Thanks for your great efforts. I use your EFI and upgrade my Xiaomi 13.3 GEN 1 on Catalian (beta6). But lots of drivers have probelems:
1. USB WiFi Adapter stop working
2. HDMI output doesn't work anymore
3. Touchpad could not do left/right click. If I click on a folder, it doesn't open the folder nor show directory property. But I could move the cursor.
4. Could not shutdown

**Comment by czg1997** [comment]
By the way, anyway to download the latest BIOS?
------------------------------------------------------------------------
Important! Use the last Bios A09 http://bbs.xiaomi.cn/t-37742666

**Comment by bossoq** [comment]
@czg1997 We haven't tested it with Catalina yet. To solve your issues, we need more information.
1. Which model of the USB WiFi? This must be the problem with the Kernel Extension (kext) of dongle. Your vendor must update their kext to support new OS.
2. Did graphic acceleration work properly? What graphics was shown in your About My Mac? If graphic acceleration work properly, I think we need to patch FrameBuffer.
3. This issue is about VoodooI2C by acidanthera. You may contact him directly.
4. Which model do you have, i5-6200U or i7-6500U? Is shutdown worked on previous version, Mojave or High Sierra? This is a known issue for i7 model. To partially fixed, you need to disable SS03 and SS04 ports (I know it sucks. You will lose USB3.0 functionality of Type C port and left port).

**Comment by johnnync13** [comment]
With betas there are always problems, because until the final date they can change the code many times

**Comment by czg1997** [comment]
Thanks for your tips. I'll do more research on catalina. Best, :)

**Comment by czg1997** [comment]
By the way, my Wi-Fi adapter is Realtek 8812AU. And CPU is i5-6200U.
